### ISSUE TITLE
Version of jwordsplitter

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#617]
```
I am not able to use decompounding together with the LanguageToolSegmenter because the
segmenter needs version 3.4 of jwordsplitter and decompounding only works with 3.2.


If I use 3.4, exception in decompounding: 
Exception in thread "main" java.lang.NoClassDefFoundError: de/abelssoft/wordtools/jWordSplitter/AbstractWordSplitter
	at ....initializeSplitterResource(...)

Caused by: java.lang.ClassNotFoundException: de.abelssoft.wordtools.jWordSplitter.AbstractWordSplitter
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)


If I use 3.2, exception in the segmenter: 

Exception in thread "main" java.lang.NoClassDefFoundError: de/abelssoft/wordtools/jwordsplitter/AbstractWordSplitter
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:191)
	at org.languagetool.Language.createLanguageObjects(Language.java:111)
	at org.languagetool.Language.getLanguages(Language.java:97)
	at org.languagetool.Language.<clinit>(Language.java:71)
	at de.tudarmstadt.ukp.dkpro.core.languagetool.LanguageToolSegmenter.process(LanguageToolSegmenter.java:45)
	at de.tudarmstadt.ukp.dkpro.core.api.segmentation.SegmenterBase.process(SegmenterBase.java:119)
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:309)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:569)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:411)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:266)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:267)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:280)
	at demo.CtestProduction.generateCTest(CtestProduction.java:82)
	at demo.CtestProduction.main(CtestProduction.java:143)
Caused by: java.lang.ClassNotFoundException: de.abelssoft.wordtools.jwordsplitter.AbstractWordSplitter
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 18 more
```

Original issue reported on code.google.com by `lisa.beinborn` on 2015-04-30 09:38:39

**Comment by reckart** [comment]
Fixed in e8f8c2d185df2fbe29ba2ebf1cba4d2dc9b69444 and 993215b9f9cfd3e396c960f7468b7098bd6c18db.

Duplicates issue #586.
